name: GH_RELEASE

on:
  push:
    tags:
      - "*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install conventional-changelog@3.1.25
        run: npm install conventional-changelog@3.1.25
      - name: Generate Changelog-current
        run: npm run changelog-current | grep -v "^>" | sed '/^$/d' > ${{ github.workspace }}-CHANGELOG.txt
      - name: Test
        run: cat ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}-CHANGELOG.txt
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}